name: Builds and runs all the tests

on:
  pull_request:
    branches: [ main ]
    paths: 
      - '**.cs'
      - '**.razor'
      - '**.cshtml'
      - '**.csproj'

env:
  DOTNET_VERSION: 6.0.x

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
