name: Builds and runs all the tests

on:
  pull_request:
    branches: [ main ]
    paths: 
      - '**.cs'
      - '**.razor'
      - '**.cshtml'
      - '**.csproj'

env:
  DOTNET_VERSION: 7.0.x

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup appsettings values
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/LemonBot.Web/appsettings.json
      env:
        AzureAdB2C.Instance: ${{ secrets.TEST_ADB2C_INSTANCE }}
        AzureAdB2C.ClientId: ${{ secrets.TEST_ADB2C_CLIENT }}
        AzureAdB2C.Domain: ${{ secrets.TEST_ADB2C_DOMAIN }}
        AzureAdB2C.SignUpSignInPolicyId: ${{ secrets.TEST_ADB2C_POLICY }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
